### ISSUE TITLE
Security issue in storybook

### ISSUE THREAD

**Issue by good-lly** [trezor/trezor-ui-components#1]
Due to integration shelljs in @storybook/react 4.1.6 is introduced security issue-> https://app.snyk.io/vuln/npm:shelljs:20140723 there is command injection. 
Not sure its a legit or just nonsense -> https://github.com/storybooks/storybook/issues/2242 It seems its on purpose.

Further investigate ...

**Comment by keip** [comment]
After some research i believe there is no security issue because storybook doesn't use the `shelljs.exec`.

@ndelangen says:
I'm pretty sure we're not using `shelljs.exec` and interpolate data from outside our domain into the command, anyway. Thus there's no possibility for command injection in our case.

I am annoyed by the warning, I do not want people to think Storybook is insecure because of this, because this is first and foremost a devDependency, and second (as i already mentioned) the way we use it doesn't allow command injection to happen.
