### ISSUE TITLE
Icons - code example is useless

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-ui-components#131]
There is a missing path even in if you copy to clipboard.

![image](https://user-images.githubusercontent.com/3112191/54722432-c7a80180-4b64-11e9-8805-350796e81c21.png)

**Comment by slowbackspace** [comment]
well, that's not how you should use the `icon` prop anyway.
The correct way is to import icons from TUC and pass selected icon to the `icon` prop. Story source is auto generated. I don't know if we can do anything about how storybook handle this.

Maybe we could allow to pass the icon by its name and do the necessary import in `Icon` component? Eg. `<Icon name="ARROW_UP" />` It would make sense since the icons in current form (object with props paths, viewbox...) are not usable outside of the `Icon` component anyway.

**Comment by keip** [comment]
@slowbackspace i agree with you, this is a much better solution. 
The icons should be imported in `Icon` component and you should send only the name of the icon to the component.

The only problem i see with this is that you are using `strings` and not `constants`.
