### ISSUE TITLE
Checkbox and switch are not clickable in storybook

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-ui-components#145]

**Comment by slowbackspace** [comment]
Could be implemented with https://stackoverflow.com/questions/45918350/how-to-update-components-props-in-storybook

**Comment by slowbackspace** [comment]
I think that in order to change the prop passed to a component (eg `isChecked`) with a click event, we need to store this var in a state and pass this state variable. This addon could help https://github.com/Sambego/storybook-state. Is it worth the trouble thought? These storybook addons seem to get quickly deprecated and could block us in future storybook upgrades.
