### ISSUE TITLE
Button with icon is not centered

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-ui-components#49]
Left padding from icon is not the same size as a right padding.
![image](https://user-images.githubusercontent.com/3112191/53735465-3a3b9080-3e87-11e9-98d9-3cb660ac5fab.png)

https://github.com/trezor/trezor-wallet/issues/422

**Comment by slowbackspace** [comment]
I am ok with the current (intended) design. Left padding should be same as button's right padding. The icon is part of the button content so it make sense to me that it is closer to the label. 
Seems like everyone is doing it the same way
https://coreui.io/docs/components/buttons/#with-icons
https://codesandbox.io/s/momwn713y8?from-embed (grommet)
https://www.w3schools.com/howto/howto_css_icon_buttons.asp (:D)

I think the problem is that visually left padding doesn't look the same as right padding  because of empty space in the icon's SVG.

<img width="676" alt="screenshot 2019-03-04 at 17 28 05" src="https://user-images.githubusercontent.com/6961901/53747211-1423e980-3ea3-11e9-9e2c-0e16c2471277.png">

Maybe we should update the svg icons so there is no empty space wrapping them?
